      - name: Parse URLs and Download Each
        run: |
          mkdir -p downloads

          urls="${{ github.event.inputs.episode_urls }}"
          IFS='|||' read -ra URL_ARRAY <<< "$urls"

          for raw_url in "${URL_ARRAY[@]}"; do
            url=$(echo "$raw_url" | xargs)
            [[ -z "$url" ]] && continue
            filename=$(basename "$url" | cut -d'?' -f1)
            echo "Downloading: $url"
            curl -L "$url" -o "downloads/$filename"
          done

      - name: Zip all downloaded episodes
        run: zip -r podcast-episodes.zip downloads/

      - name: Upload zipped podcasts as artifact
        uses: actions/upload-artifact@v4
        with:
          name: podcast-episodes
          path: podcast-episodes.zip
