name: Download Podcast Episode

on:
  workflow_dispatch:
    inputs:
      episode_url:
        description: 'URL of the Podcast Episode'
        required: true
        default: 'https://traffic.libsyn.com/secure/meaningfulpeoplepodcast/Shoff_1_june_chicago_final.mp3?dest-id=1900811'

jobs:
  download_podcast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download podcast episode
        run: |
          curl -L -o "episode.mp3" "${{ github.event.inputs.episode_url }}"
      
      - name: Upload the episode as artifact
        uses: actions/upload-artifact@v3
        with:
          name: podcast-episode
          path: episode.mp3
