name: Download and Zip Podcast Episodes

on:
  workflow_dispatch:
    inputs:
      episode_urls:
        description: "Paste URLs separated by |||"
        required: true
        default: ""

jobs:
  download_and_zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create download directory
        run: mkdir -p downloads

      - name: Download each episode
        run: |
          urls="${{ github.event.inputs.episode_urls }}"
          IFS='|||' read -ra URL_ARRAY <<< "$urls"

          for raw_url in "${URL_ARRAY[@]}"; do
            url=$(echo "$raw_url" | xargs)
            [[ -z "$url" ]] && continue
            filename=$(basename "$url" | cut -d'?' -f1)
            echo "Downloading: $url"
            curl -L "$url" -o "downloads/$filename"
          done

      - name: Zip all downloaded episodes
        run: zip -r podcast-episodes.zip downloads/

      - name: Upload zipped episodes as artifact
        uses: actions/upload-artifact@v4
        with:
          name: podcast-episodes
          path: podcast-episodes.zip
