name: Download File

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'URL of the file to download'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download file from URL
        run: |
          curl -L -o downloaded_file "$FILE_URL"
        env:
          FILE_URL: ${{ github.event.inputs.file_url }}
      - name: Show downloaded file info
        run: ls -l downloaded_file
